### ISSUE TITLE
blacklist or whitelist for px?

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/dom-css#1]
TweenLite uses a whitelist to only suffix certain properties [[1]](https://github.com/greensock/GreenSock-JS/blob/04774cbb6bf3c255dcd388ec530f448025a45df5/src/uncompressed/plugins/CSSPlugin.js#L39)

jQuery uses a blacklist to suffix all properties except specific ones [[2]](https://github.com/jquery/jquery/blob/740e190223d19a114d5373758127285d14d6b71e/src/css.js#L230-L243)

Which approach is best for a module like this? hmm

**Comment by maxtherocket** [comment]
I think a whitelist is better, as new properties become available you would have to always be in the know of what to blacklist and that can actually break things if you don't blacklist a specific property. For the whitelist, it's not a big deal if a new property is not 'px'ified, the dev could just add it herself. +1 for whitelisting

**Comment by mikkoh** [comment]
@mattdesl in my mind it's better to white list as there's way less numeric items you want to add `'px'` to.

Your black list will have more items and harder to manage.

**Comment by mattdesl** [comment]
The behaviour is now the same as React & jQuery, using a blacklist. Pushed to `2.x` since it is a major bump.
